<?php

	//application details
		$apps[$x]['name'] = "Business Reports";
		$apps[$x]['uuid'] = "4c2e5b8a-7f9a-4d3e-b1c6-8a9e7f3d2b1c";
		$apps[$x]['category'] = "Reports";
		$apps[$x]['subcategory'] = "";
		$apps[$x]['version'] = "1.0.0";
		$apps[$x]['license'] = "Mozilla Public License 1.1";
		$apps[$x]['url'] = "https://www.fusionpbx.com";
		$apps[$x]['description']['en-us'] = "Business-grade call reporting with saved views, inbound/outbound/local classification, and dynamic filtering.";
		$apps[$x]['description']['en-gb'] = "Business-grade call reporting with saved views, inbound/outbound/local classification, and dynamic filtering.";

	//permission details
		$y = 0;
		$apps[$x]['permissions'][$y]['name'] = "business_report_view";
		$apps[$x]['permissions'][$y]['menu']['uuid'] = "a1b2c3d4-e5f6-7890-a1b2-c3d4e5f67890";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$apps[$x]['permissions'][$y]['groups'][] = "user";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "business_report_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "business_report_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "business_report_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";

	//schema details - v_report_views table
		$y = 0;
		$apps[$x]['db'][$y]['table']['name'] = "v_report_views";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "report_view_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "name";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Name of the report view";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "description";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Description of the report view";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "definition_json";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "JSON definition of filters, groupings, and metrics";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "is_public";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "boolean";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Whether the view is public or private";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "created_by";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "User who created the view";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "created_at";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "timestamp";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "When the view was created";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "updated_at";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamptz";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "timestamp";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "When the view was last updated";

	//schema details - v_report_view_acl table
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_report_view_acl";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "report_view_acl_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "report_view_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_report_views";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "report_view_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "user_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "User who has access (null for role-based)";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "group_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Group that has access (null for user-based)";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "can_view";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "boolean";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Permission to view the report";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "can_edit";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "boolean";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Permission to edit the report";

?>
